services:
  - type: web
    name: pos-pro-vietnam
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: PORT
        value: 10000
