const fs = require('fs');
const path = require('path');

const indexHtmlPath = path.join(__dirname, '..', 'public', 'index.html');
const mountJsPath = path.join(__dirname, '..', 'public', 'js', 'mount.js');

const htmlContent = fs.readFileSync(indexHtmlPath, 'utf8');

// Match everything inside <div id="app" ...> ... </div> <!-- /#app: Zalo Mini App Root Container -->
const startMarker = '<div id="app" class="w-full h-full flex flex-col overflow-hidden">';
const endMarker = '</div> <!-- /#app: Zalo Mini App Root Container -->';

const startIndex = htmlContent.indexOf(startMarker);
const endIndex = htmlContent.indexOf(endMarker);

if (startIndex === -1 || endIndex === -1) {
  console.error('Error: Could not find #app boundaries in public/index.html');
  process.exit(1);
}

const innerHtml = htmlContent.substring(startIndex + startMarker.length, endIndex).trim();

const mountJsContent = `// =============================================================
// ZALO MINI APP DYNAMIC MOUNT & DEPENDENCY LOADER
// Auto-generated by scripts/build-mount.js - Do NOT edit directly
// =============================================================

window.__POS_HTML_TEMPLATE__ = ${JSON.stringify(innerHtml)};

(function() {
  function ensureDependencies() {
    // 1. Tailwind CSS
    if (!document.querySelector('script[src*="tailwindcss"]')) {
      const tw = document.createElement('script');
      tw.src = 'https://cdn.tailwindcss.com';
      document.head.appendChild(tw);
    }
    // 2. Font Awesome
    if (!document.querySelector('link[href*="font-awesome"]')) {
      const fa = document.createElement('link');
      fa.rel = 'stylesheet';
      fa.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css';
      document.head.appendChild(fa);
    }
    // 3. Chart.js
    if (!document.querySelector('script[src*="chart.js"]')) {
      const c = document.createElement('script');
      c.src = 'https://cdn.jsdelivr.net/npm/chart.js';
      document.head.appendChild(c);
    }
    // 4. Confetti
    if (!document.querySelector('script[src*="canvas-confetti"]')) {
      const cf = document.createElement('script');
      cf.src = 'https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js';
      document.head.appendChild(cf);
    }
  }

  function mountPosApp() {
    let appEl = document.getElementById('app');
    if (!appEl) {
      appEl = document.createElement('div');
      appEl.id = 'app';
      document.body.appendChild(appEl);
    }

    // Apply baseline container styles
    document.body.className = 'bg-slate-100 text-slate-800 h-screen flex flex-col overflow-hidden select-none';
    appEl.className = 'w-full h-full flex flex-col overflow-hidden';

    // If screen-tables does not exist, inject the full POS UI template
    if (!document.getElementById('screen-tables')) {
      ensureDependencies();
      appEl.innerHTML = window.__POS_HTML_TEMPLATE__;
    }
  }

  // Mount immediately if DOM is ready, otherwise on DOMContentLoaded
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mountPosApp);
  } else {
    mountPosApp();
  }
})();
`;

fs.writeFileSync(mountJsPath, mountJsContent, 'utf8');
console.log('Successfully generated public/js/mount.js! Template size: ' + innerHtml.length + ' chars');
